import { Document, Page, Text, View, StyleSheet, pdf } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#17211E" },
  clinicName: { fontSize: 18, marginBottom: 2 },
  doctorName: { fontSize: 11, color: "#4C5A56", marginBottom: 16 },
  divider: { borderBottomWidth: 1, borderBottomColor: "#DBE2DE", marginBottom: 16 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 4 },
  label: { color: "#7C8985" },
  rxLabel: { fontSize: 14, marginTop: 20, marginBottom: 10 },
  rxBody: { fontSize: 12, lineHeight: 1.6 },
  footer: { position: "absolute", bottom: 30, left: 40, right: 40, fontSize: 9, color: "#7C8985", borderTopWidth: 1, borderTopColor: "#DBE2DE", paddingTop: 8 },
});

export function PrescriptionDoc({ clinicName, doctorName, regNo, patientName, patientAge, patientGender, date, rxText }: {
  clinicName: string; doctorName: string; regNo?: string; patientName: string; patientAge?: number; patientGender?: string; date: string; rxText: string;
}) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.clinicName}>{clinicName}</Text>
        <Text style={styles.doctorName}>{doctorName}{regNo ? ` · Reg. No. ${regNo}` : ""}</Text>
        <View style={styles.divider} />
        <View style={styles.row}><Text style={styles.label}>Patient</Text><Text>{patientName}{patientAge ? `, ${patientAge}` : ""}{patientGender ? ` (${patientGender})` : ""}</Text></View>
        <View style={styles.row}><Text style={styles.label}>Date</Text><Text>{date}</Text></View>
        <Text style={styles.rxLabel}>℞</Text>
        <Text style={styles.rxBody}>{rxText}</Text>
        <Text style={styles.footer} fixed>Generated by ScheduRx — for the named patient only.</Text>
      </Page>
    </Document>
  );
}

export async function renderPrescriptionPdf(props: Parameters<typeof PrescriptionDoc>[0]): Promise<Blob> {
  return pdf(<PrescriptionDoc {...props} />).toBlob();
}
